process.env.VITE_USE_EMULATORS = 'true';
process.env.VITE_EMULATOR_HOST = process.env.VITE_EMULATOR_HOST || '127.0.0.1';
process.env.VITE_AUTH_EMULATOR_PORT = process.env.VITE_AUTH_EMULATOR_PORT || '9099';
process.env.VITE_FIRESTORE_EMULATOR_PORT = process.env.VITE_FIRESTORE_EMULATOR_PORT || '8080';
process.env.VITE_STORAGE_EMULATOR_PORT = process.env.VITE_STORAGE_EMULATOR_PORT || '9199';
process.env.VITE_FUNCTIONS_EMULATOR_PORT = process.env.VITE_FUNCTIONS_EMULATOR_PORT || '5001';
