const NOTIFICATION_EVENTS = Object.freeze({
  POLL_CREATED: "POLL_CREATED",
  POLL_INVITE_SENT: "POLL_INVITE_SENT",
  POLL_INVITE_ACCEPTED: "POLL_INVITE_ACCEPTED",
  POLL_INVITE_DECLINED: "POLL_INVITE_DECLINED",
  POLL_INVITE_REVOKED: "POLL_INVITE_REVOKED",
  VOTE_SUBMITTED: "VOTE_SUBMITTED",
  VOTE_REMINDER: "VOTE_REMINDER",
  POLL_READY_TO_FINALIZE: "POLL_READY_TO_FINALIZE",
  POLL_ALL_VOTES_IN: "POLL_ALL_VOTES_IN",
  POLL_FINALIZED: "POLL_FINALIZED",
  POLL_REOPENED: "POLL_REOPENED",
  POLL_CANCELLED: "POLL_CANCELLED",
  POLL_RESTORED: "POLL_RESTORED",
  POLL_DELETED: "POLL_DELETED",
  SLOT_CHANGED: "SLOT_CHANGED",
  DISCORD_NUDGE_SENT: "DISCORD_NUDGE_SENT",
  FRIEND_REQUEST_SENT: "FRIEND_REQUEST_SENT",
  FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
  FRIEND_REQUEST_DECLINED: "FRIEND_REQUEST_DECLINED",
  FRIEND_REMOVED: "FRIEND_REMOVED",
  GROUP_INVITE_SENT: "GROUP_INVITE_SENT",
  GROUP_INVITE_ACCEPTED: "GROUP_INVITE_ACCEPTED",
  GROUP_INVITE_DECLINED: "GROUP_INVITE_DECLINED",
  GROUP_MEMBER_REMOVED: "GROUP_MEMBER_REMOVED",
  GROUP_MEMBER_LEFT: "GROUP_MEMBER_LEFT",
  GROUP_DELETED: "GROUP_DELETED",
});

const LEGACY_NOTIFICATION_ALIASES = Object.freeze({
  FRIEND_REQUEST: NOTIFICATION_EVENTS.FRIEND_REQUEST_SENT,
  FRIEND_ACCEPTED: NOTIFICATION_EVENTS.FRIEND_REQUEST_ACCEPTED,
  POLL_INVITE: NOTIFICATION_EVENTS.POLL_INVITE_SENT,
  SESSION_INVITE: NOTIFICATION_EVENTS.POLL_INVITE_SENT,
  SESSION_JOINED: NOTIFICATION_EVENTS.POLL_INVITE_ACCEPTED,
  SESSION_FINALIZED: NOTIFICATION_EVENTS.POLL_FINALIZED,
  GROUP_INVITE: NOTIFICATION_EVENTS.GROUP_INVITE_SENT,
  GROUP_INVITE_ACCEPTED: NOTIFICATION_EVENTS.GROUP_INVITE_ACCEPTED,
});

const resolveGroupMemberChange = (metadata) => {
  if (!metadata || typeof metadata !== "object") return null;
  if (metadata.action === "removed") return NOTIFICATION_EVENTS.GROUP_MEMBER_REMOVED;
  if (metadata.action === "left") return NOTIFICATION_EVENTS.GROUP_MEMBER_LEFT;
  return null;
};

const resolveNotificationEventType = (eventType, metadata) => {
  if (!eventType) return null;
  if (NOTIFICATION_EVENTS[eventType]) return eventType;
  if (eventType === "GROUP_MEMBER_CHANGE") return resolveGroupMemberChange(metadata);
  return LEGACY_NOTIFICATION_ALIASES[eventType] || null;
};

const isNotificationEvent = (eventType) => Boolean(NOTIFICATION_EVENTS[eventType]);

module.exports = {
  NOTIFICATION_EVENTS,
  LEGACY_NOTIFICATION_ALIASES,
  resolveNotificationEventType,
  isNotificationEvent,
};
